### PR TITLE
Add version test

### PR DESCRIPTION
**Pull request by dhirschfeld**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by dhirschfeld** [comment]
I'm curious if this (slightly hacky) test will work :eyes:

**Comment by giswqs** [comment]
@dhirschfeld I just uncommented `pip check` and the build failed. Curious to see if your solution works. Thank you for your help.

**Comment by dhirschfeld** [comment]
A successful failure! :tada:
```
import: 'autogluon.tabular'
import: 'autogluon.tabular'
+ python -c 'from autogluon.tabular import __version__ as v; assert v == '\''0.6.2'\'', f'\''{v} != 0.6.2'\'''
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AssertionError: 0.6.2b20230120 != 0.6.2
Tests failed for autogluon.tabular-0.6.2-pyhd8ed1ab_2.conda - moving package to /home/conda/feedstock_root/build_artifacts/broken
```

**Comment by giswqs** [comment]
@dhirschfeld Perfect! Thank you.

**Comment by dhirschfeld** [comment]
> @dhirschfeld Perfect! Thank you.

Happy to help! :)

**Comment by Innixma** [comment]
Thanks for this @dhirschfeld !!

**Pull request merged**
